version: "3.7"

services:
  broker:
    image: node:16
    ports: 
      - 3000:80
    volumes:
      - ./tmp/logs:/app/logs
    command: > 
      bash -c "cd /app &&
      yarn add https://github.com/jamesgopsill/bam-living-lab-broker &&
      node node_modules/@jamesgopsill/bam-living-lab-broker/dist --sk socket-key --lk log-key --lp /app/logs"

